version: '1'
services:
  #mssql docker
  ekino-sql:
    ulimits:
      memlock:
        soft: -1
        hard: -1
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=admin123!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
      - 1433
    networks:
      - ekinonet

  ekino-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=ekino-sql,1433;Database=eKino;User=sa;Password=admin123!;ConnectRetryCount=0;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 7127:7127
    networks:
      - ekinonet
    links:
      - ekino-sql
    depends_on:
      - ekino-sql

networks:
  ekinonet:
    driver: bridge
